### ISSUE TITLE
Your project is too difficult to use

### ISSUE THREAD

**Issue by haisheng666** [VinciGit00/Scrapegraph-ai#175]
Your project is too difficult to use. Even the sample code doesn’t work. Please fix the bugs.

(scrape_graph_ai_project) lhs@lhs-jijia-u2204:scrape_graph_ai_project$ python3 sga_2.py 
/home/lhs/PycharmVenv/scrape_graph_ai_project/lib/python3.10/site-packages/scrapegraphai/utils/remover.py:26: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(html_content, 'html.parser')
{'articles': []}

**Comment by PeriniM** [comment]
Hey @haisheng666 we have fixed the bug with the new version, try to install it from scratch in a virtual env ;)
0ca52b1

**Comment by zpengcom** [comment]
I just tried Ollama or the same is still wrong
`I:\AI\Scrapegraph-ai\scrapegraphai\utils\remover.py:26: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(html_content, 'html.parser')
>>> print(result)
{'articles': []}`
